# Generated by Django 5.0.4 on 2024-11-17 00:21

import re
from django.db import migrations, models
from django.db.models import Q
from django.db.models import F, Func, Value


class Cast(Func):
    function = "CAST"
    template = "%(expressions)s::%(db_type)s"

    def __init__(self, expression, db_type, **extra):
        super().__init__(expression, db_type=db_type, **extra)


def populate_and_clean_content_text(apps, schema_editor):
    SimpleLog = apps.get_model("zane_api", "SimpleLog")

    if schema_editor.connection.vendor != "postgresql":
        ansi_re = re.compile(r"\u001b\[[0-9;]*[a-zA-Z]")
        quote_re = re.compile(r'^"(.*)"$')
        qs = SimpleLog.objects.filter(~Q(source="PROXY"), content_text__isnull=False).only("id", "content", "content_text")
        for obj in qs.iterator(chunk_size=1000):
            try:
                text = obj.content_text or ""
                text = text.replace(r"\\", "\\")
                text = text.replace(r'\"', '"')
                m = quote_re.match(text)
                if m:
                    text = m.group(1)
                text = ansi_re.sub("", text)
                obj.content_text = text
                obj.save(update_fields=["content_text"])
            except Exception:
                continue
        return

    ansi_pattern = Value(r"\\u001b\[[0-9;]*[a-zA-Z]")
    replacement = Value("")
    flags = Value("g")

    # PostgreSQL path
    SimpleLog.objects.filter(~Q(source="PROXY"), content_text__isnull=False).update(
        content_text=Func(
            Func(
                Func(
                    Func(
                        Cast(F("content"), db_type="text"),  # Cast content JSON to text
                        Value(r"\\"),  # Replace escaped backslashes `\\` `\`
                        Value("\\"),
                        function="REPLACE",
                    ),
                    Value(r"\""),  # Replace escaped double quotes
                    Value('"'),
                    function="REPLACE",
                ),
                Value(r'^"(.*)"$'),  # Regex to match quotes at the start and end
                Value(r"\1"),  # Remove quotes, keep inner content
                function="REGEXP_REPLACE",
            ),
            ansi_pattern,
            replacement,
            flags,
            function="REGEXP_REPLACE",
            output_field=models.TextField(),
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0164_auto_20241117_0325"),
    ]

    operations = [
        migrations.RunPython(
            populate_and_clean_content_text,
            reverse_code=migrations.RunPython.noop,  # No reverse operation needed for deletion
        ),
    ]
